"""Generate AgentCore Cedar policies from AgentAudit findings.

Schema follows the documented AgentCore Policy Cedar model:

* principal — ``AgentCore::IamEntity`` (AWS_IAM gateways) or
  ``AgentCore::OAuthUser`` (OAuth gateways)
* action    — ``AgentCore::Action::"<TargetName>___<tool_name>"`` (three
  underscores between target and tool, per the AgentCore action naming)
* resource  — ``AgentCore::Gateway::"<gateway ARN>"``

Design note — why we forbid *one leg* rather than "the sequence":
AgentCore Cedar authorizes a **single tool call** at a time. `context` exposes
the current call's `input`, not the session's prior tool calls, so there is no
`context.tool_sequence` to test against. The correct, schema-valid remediation
for a capability pair is therefore to forbid the **egress leg** (the tool that
can move data out), which breaks the exfiltration chain while leaving the
non-egress tool usable. Cedar's forbid-wins semantics guarantee the denial
overrides any permit.
"""

from __future__ import annotations

import re
from typing import Any

# Capabilities that constitute the "egress leg" of an exfiltration chain,
# most-dangerous first — this is the leg we deny.
_EGRESS_CAPABILITIES = ("NETWORK",)

_SAFE_NAME = re.compile(r"[^A-Za-z0-9_-]")


def _as_dict(finding: Any) -> dict:
    """Accept a Finding dataclass or a plain dict."""
    if isinstance(finding, dict):
        return finding
    if hasattr(finding, "to_dict"):
        return finding.to_dict()
    raise TypeError(f"unsupported finding type: {type(finding)!r}")


def policy_name_for(finding: Any) -> str:
    """Stable, API-safe policy name derived from the finding."""
    f = _as_dict(finding)
    md = f.get("metadata") or {}
    pattern = md.get("pattern", f.get("detector", "finding"))
    tool = md.get("tool_b") or md.get("tool") or "tool"
    raw = f"agentaudit-{pattern}-{tool}"
    return _SAFE_NAME.sub("-", raw)[:64]


def _egress_tool(md: dict) -> tuple[str, str]:
    """Return (tool_to_deny, its_capability) — the egress leg of the pair."""
    pairs = [
        (md.get("tool_a"), md.get("capability_a")),
        (md.get("tool_b"), md.get("capability_b")),
    ]
    for cap in _EGRESS_CAPABILITIES:
        for tool, tool_cap in pairs:
            if tool and tool_cap == cap:
                return tool, tool_cap
    # No explicit egress capability: deny the second leg as the riskier one.
    tool, cap = pairs[1] if pairs[1][0] else pairs[0]
    return tool or "unknown_tool", cap or "UNKNOWN"


def generate_cedar_policy(
    finding: dict,
    gateway_arn: str,
    target_name: str = "AgentAudit",
    principal_type: str = "AgentCore::IamEntity",
) -> str:
    """Build a Cedar ``forbid`` statement that blocks a finding's dangerous call.

    Args:
        finding: a finding dict (or Finding) — uses ``metadata`` for the tool
            names and capabilities, and ``severity`` for the annotation.
        gateway_arn: the real ARN of the AgentCore Gateway to scope the policy to.
        target_name: the gateway target name that prefixes tool actions.
        principal_type: ``AgentCore::IamEntity`` or ``AgentCore::OAuthUser``.

    Returns:
        Cedar policy text (a single ``forbid`` statement with a comment header).
    """
    f = _as_dict(finding)
    md = f.get("metadata") or {}
    detector = f.get("detector", "unknown")
    severity = f.get("severity", "unknown")

    if detector == "exfiltration-capability-pair":
        deny_tool, deny_cap = _egress_tool(md)
        other = md.get("tool_a") if deny_tool == md.get("tool_b") else md.get("tool_b")
        rationale = (
            f"{md.get('tool_a')} ({md.get('capability_a')}) + "
            f"{md.get('tool_b')} ({md.get('capability_b')}) forms an exfiltration path; "
            f"denying the egress leg '{deny_tool}' breaks the chain"
        )
    else:
        deny_tool = md.get("tool") or md.get("tool_b") or "unknown_tool"
        other = None
        rationale = f"{detector} on tool '{deny_tool}'"

    action = f'AgentCore::Action::"{target_name}___{deny_tool}"'

    header = (
        "// Generated by AgentAudit — automatic remediation\n"
        f"// detector : {detector}\n"
        f"// severity : {severity}\n"
        f"// pattern  : {md.get('pattern', 'n/a')}\n"
        f"// rationale: {rationale}\n"
    )
    if other:
        header += f"// paired with: {other}\n"

    policy = (
        f"{header}"
        "forbid(\n"
        f"  principal is {principal_type},\n"
        f"  action == {action},\n"
        f'  resource == AgentCore::Gateway::"{gateway_arn}"\n'
        ");"
    )
    return policy
